/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Name.inc
 */
public final class Formulas extends javax.swing.JFrame {

    /**
     * Creates new form Formulas
     */
    public Formulas() {
        initComponents();
        this.setLocationRelativeTo(null);
        JB_e.setIcon(setIconoF("/Imagenes/Formulas/e.png", JB_e));
        JB_n.setIcon(setIconoF("/Imagenes/Formulas/n.png", JB_n));
        JB_S.setIcon(setIconoF("/Imagenes/Formulas/s.png", JB_S));
        JB_W.setIcon(setIconoF("/Imagenes/Formulas/w.png", JB_W));
        JB_Y.setIcon(setIconoF("/Imagenes/Formulas/Y.png", JB_e));
        JB_Yd.setIcon(setIconoF("/Imagenes/Formulas/Yd.png", JB_Yd));
        JB_Gs.setIcon(setIconoF("/Imagenes/Formulas/Gs.png", JB_Gs));
        JB_Vt.setIcon(setIconoF("/Imagenes/Formulas/Vt.png", JB_Vt));
        JB_Wt.setIcon(setIconoF("/Imagenes/Formulas/Wt.png", JB_Wt));
        JB_TS.setIcon(setIconoF("/Imagenes/Formulas/tS.png", JB_TS));
        JB_TnYd.setIcon(setIconoF("/Imagenes/Formulas/nYd.png", JB_TnYd));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JB_e = new javax.swing.JButton();
        JB_W = new javax.swing.JButton();
        JB_S = new javax.swing.JButton();
        JB_n = new javax.swing.JButton();
        JB_Y = new javax.swing.JButton();
        JB_Yd = new javax.swing.JButton();
        JB_Gs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLABEL4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JB_Vt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JB_Wt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JB_TnYd = new javax.swing.JButton();
        JB_TS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Fórmulas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));
        getContentPane().add(JB_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 60));
        getContentPane().add(JB_W, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 147, 60));
        getContentPane().add(JB_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 147, 60));
        getContentPane().add(JB_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, 60));
        getContentPane().add(JB_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 60));
        getContentPane().add(JB_Yd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, 60));
        getContentPane().add(JB_Gs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 147, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Relación de vacíos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Porosidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        JLABEL4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLABEL4.setText("Humedad");
        getContentPane().add(JLABEL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Grado de Saturación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Gravedad Esp. Sólido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Peso Esp. Húmedo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Peso Esp. Seco");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
        getContentPane().add(JB_Vt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 150, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Volumen Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));
        getContentPane().add(JB_Wt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 150, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("PesoTotal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Tablas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));
        getContentPane().add(JB_TnYd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 360, 180));
        getContentPane().add(JB_TS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 420, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulas().setVisible(true);
            }
        });
    }
    public Icon setIconoF(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Gs;
    private javax.swing.JButton JB_S;
    private javax.swing.JButton JB_TS;
    private javax.swing.JButton JB_TnYd;
    private javax.swing.JButton JB_Vt;
    private javax.swing.JButton JB_W;
    private javax.swing.JButton JB_Wt;
    private javax.swing.JButton JB_Y;
    private javax.swing.JButton JB_Yd;
    private javax.swing.JButton JB_e;
    private javax.swing.JButton JB_n;
    private javax.swing.JLabel JLABEL4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
