/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Class.*;

/**
 *
 * @author Alexis
 */
public class Interface extends javax.swing.JFrame {

    private RelacionesV_P Rel_V_P = new RelacionesV_P();
    private Volumen volumen = new Volumen();
    private Peso peso = new Peso();

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        //TxtArea_Resultado.setEditable(false);
        //TxtArea_Resultado.setLineWrap(true);

        //
        jtVol_Vacio.setEnabled(false);
        jtVol_Agua.setEnabled(false);
        jtVol_Aire.setEnabled(false);
        jtVol_Total.setEnabled(false);
        jtVol_solidos.setEnabled(false);
        //
        jtPes_Agua.setEnabled(false);
        jtPes_Aire.setEnabled(false);
        jtPes_Solid.setEnabled(false);
        jtPes_Total.setEnabled(false);
        flech3.setVisible(false);
        texttitmuestra1.setVisible(true);
        texttitmuestra2.setVisible(false);

        jtVol_Agua.setText("0");
        jtVol_Aire.setText("0");
        jtVol_Total.setText("0");
        jtVol_Vacio.setText("0");
        jtVol_solidos.setText("0");
        //
    }
    private int count = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulodelAplicativo = new javax.swing.JLabel();
        jPanelGraficaMuestra = new javax.swing.JPanel();
        jLabelPESO = new javax.swing.JLabel();
        jLabelVOLUMEN = new javax.swing.JLabel();
        jLabelVw = new javax.swing.JLabel();
        jLabelFASESOLIDA = new javax.swing.JLabel();
        jLabelWt = new javax.swing.JLabel();
        jLabelWs = new javax.swing.JLabel();
        graf_Vw = new javax.swing.JTextField();
        graf_Wt = new javax.swing.JTextField();
        graf_Ww = new javax.swing.JTextField();
        jLabelWw = new javax.swing.JLabel();
        graf_Ws = new javax.swing.JTextField();
        jLabelVs = new javax.swing.JLabel();
        jLabelVt = new javax.swing.JLabel();
        graf_Vs = new javax.swing.JTextField();
        graf_Vt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        flech2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        flech1 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        flech3 = new javax.swing.JPanel();
        texttitmuestra1 = new javax.swing.JLabel();
        texttitmuestra2 = new javax.swing.JLabel();
        jLabelFASELIQUIDA = new javax.swing.JLabel();
        panelGaseoso = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        graf_Wa = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        graf_Vv = new javax.swing.JTextField();
        graf_Va = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtVol_Agua = new javax.swing.JTextField();
        jtVol_Total = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtVol_solidos = new javax.swing.JTextField();
        jtVol_Aire = new javax.swing.JTextField();
        textaire = new javax.swing.JLabel();
        jtVol_Vacio = new javax.swing.JTextField();
        jCB_VolAire = new javax.swing.JCheckBox();
        CB_VolTotal = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        textaire2 = new javax.swing.JLabel();
        jtPes_Total = new javax.swing.JTextField();
        jtPes_Agua = new javax.swing.JTextField();
        jtPes_Solid = new javax.swing.JTextField();
        jtPes_Aire = new javax.swing.JTextField();
        jCB_PesoAire = new javax.swing.JCheckBox();
        CB_PesoTotal = new javax.swing.JCheckBox();
        panelQCalc = new javax.swing.JPanel();
        jPanelRelacionesVolumetricas = new javax.swing.JPanel();
        jCBRelacionVacio = new javax.swing.JCheckBox();
        jCBPorosidad = new javax.swing.JCheckBox();
        jCBGradoSaturacion = new javax.swing.JCheckBox();
        jPanelRelacionesGravimetricas = new javax.swing.JPanel();
        jCBContenidoHumedad = new javax.swing.JCheckBox();
        jCBPesoEspecifico = new javax.swing.JCheckBox();
        jCBPesoEspecificoSeco = new javax.swing.JCheckBox();
        jCBGravedadEspecifica = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jButtonNormal = new javax.swing.JButton();
        jButtonSaturado = new javax.swing.JButton();
        jPanelResultados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea_Resultado = new javax.swing.JTextArea();
        B_Calcular = new javax.swing.JButton();
        B_Procedimiento = new javax.swing.JButton();
        B_Formulas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulodelAplicativo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelTitulodelAplicativo.setText("CALCULO VOLUMETRICO Y GRAVIMETRICO DEL SUELO");
        getContentPane().add(jLabelTitulodelAplicativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 520, -1));

        jPanelGraficaMuestra.setBackground(new java.awt.Color(255, 204, 51));
        jPanelGraficaMuestra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPESO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPESO.setText("PESO");
        jPanelGraficaMuestra.add(jLabelPESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 80, -1));

        jLabelVOLUMEN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelVOLUMEN.setText("VOLUMEN");
        jPanelGraficaMuestra.add(jLabelVOLUMEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 130, -1));

        jLabelVw.setText("Vw");
        jPanelGraficaMuestra.add(jLabelVw, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 170, 20, -1));

        jLabelFASESOLIDA.setBackground(new java.awt.Color(153, 51, 0));
        jLabelFASESOLIDA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFASESOLIDA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFASESOLIDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFASESOLIDA.setText("FASE SOLIDA");
        jLabelFASESOLIDA.setOpaque(true);
        jPanelGraficaMuestra.add(jLabelFASESOLIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, 90));

        jLabelWt.setText("Wt");
        jPanelGraficaMuestra.add(jLabelWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabelWs.setText("Ws");
        jPanelGraficaMuestra.add(jLabelWs, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));
        jPanelGraficaMuestra.add(graf_Vw, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 50, -1));
        jPanelGraficaMuestra.add(graf_Wt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 50, -1));
        jPanelGraficaMuestra.add(graf_Ww, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 40, -1));

        jLabelWw.setText("Ww");
        jPanelGraficaMuestra.add(jLabelWw, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));
        jPanelGraficaMuestra.add(graf_Ws, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 50, -1));

        jLabelVs.setText("Vs");
        jPanelGraficaMuestra.add(jLabelVs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabelVt.setText("Vt");
        jPanelGraficaMuestra.add(jLabelVt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanelGraficaMuestra.add(graf_Vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 50, -1));
        jPanelGraficaMuestra.add(graf_Vt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 30));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 30));

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, 50));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, -1));

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 40, -1));

        flech2.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(flech2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 20, -1));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 40, -1));

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 140, -1));

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, 20));

        jPanel25.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, -1));

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 30));

        flech1.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(flech1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 70));

        jPanel28.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, 20));

        jPanel27.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 110));

        jPanel29.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, 110));

        jPanel35.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 10, 30));

        jPanel24.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 10, 30));

        jPanel26.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, -1));

        jPanel31.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 10, 30));

        jPanel32.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 100, -1));

        flech3.setBackground(new java.awt.Color(0, 0, 0));
        jPanelGraficaMuestra.add(flech3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, -1));

        texttitmuestra1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        texttitmuestra1.setText("Muestra Normal");
        jPanelGraficaMuestra.add(texttitmuestra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        texttitmuestra2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        texttitmuestra2.setText("Muestra Saturado");
        jPanelGraficaMuestra.add(texttitmuestra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabelFASELIQUIDA.setBackground(new java.awt.Color(0, 102, 204));
        jLabelFASELIQUIDA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFASELIQUIDA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFASELIQUIDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFASELIQUIDA.setText("FASE LIQUIDA");
        jLabelFASELIQUIDA.setOpaque(true);
        jPanelGraficaMuestra.add(jLabelFASELIQUIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 90));

        panelGaseoso.setBackground(new java.awt.Color(255, 204, 51));
        panelGaseoso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setText("Vv");
        panelGaseoso.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        panelGaseoso.add(graf_Wa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 40, -1));

        jLabel55.setText("Wa");
        panelGaseoso.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
        panelGaseoso.add(graf_Vv, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, -1));
        panelGaseoso.add(graf_Va, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 50, -1));

        jLabel58.setText("Va");
        panelGaseoso.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jPanel39.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 30));

        jPanel48.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 20));

        jPanel50.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, -1));

        jPanel54.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 120));

        jPanel55.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, -1));

        jPanel57.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 30));

        jPanel58.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 120));

        jPanel59.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 80));

        jPanel61.setBackground(new java.awt.Color(0, 0, 0));
        panelGaseoso.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 40));

        jLabel12.setBackground(new java.awt.Color(0, 102, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("FASE LIQUIDA");
        jLabel12.setOpaque(true);
        panelGaseoso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 90));

        jLabel6.setBackground(new java.awt.Color(0, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FASE LIQUIDA");
        jLabel6.setOpaque(true);
        panelGaseoso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, 90));

        jPanelGraficaMuestra.add(panelGaseoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 120));

        getContentPane().add(jPanelGraficaMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 530, 350));

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanelDatos.setToolTipText("Datos");
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Volumen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Volumen de vacíos");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel22.setText("Volumen total");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel23.setText("Volumen de agua");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jtVol_Agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtVol_AguaActionPerformed(evt);
            }
        });
        jtVol_Agua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtVol_AguaKeyReleased(evt);
            }
        });
        jPanel3.add(jtVol_Agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 70, -1));

        jtVol_Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtVol_TotalKeyReleased(evt);
            }
        });
        jPanel3.add(jtVol_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 70, -1));

        jLabel24.setText("Volumen de sólidos");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtVol_solidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtVol_solidosActionPerformed(evt);
            }
        });
        jtVol_solidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtVol_solidosKeyReleased(evt);
            }
        });
        jPanel3.add(jtVol_solidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jtVol_Aire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtVol_AireActionPerformed(evt);
            }
        });
        jtVol_Aire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtVol_AireKeyReleased(evt);
            }
        });
        jPanel3.add(jtVol_Aire, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, -1));

        textaire.setText("Volumen del aire");
        jPanel3.add(textaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jtVol_Vacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtVol_VacioActionPerformed(evt);
            }
        });
        jtVol_Vacio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtVol_VacioKeyReleased(evt);
            }
        });
        jPanel3.add(jtVol_Vacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        jCB_VolAire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_VolAireActionPerformed(evt);
            }
        });
        jPanel3.add(jCB_VolAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        CB_VolTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_VolTotalActionPerformed(evt);
            }
        });
        jPanel3.add(CB_VolTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 200));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("Peso de agua");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel27.setText("Peso total");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel28.setText("Peso de sólidos");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        textaire2.setText("Peso del aire");
        jPanel4.add(textaire2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jtPes_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPes_TotalActionPerformed(evt);
            }
        });
        jtPes_Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPes_TotalKeyReleased(evt);
            }
        });
        jPanel4.add(jtPes_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, -1));

        jtPes_Agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPes_AguaActionPerformed(evt);
            }
        });
        jtPes_Agua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPes_AguaKeyReleased(evt);
            }
        });
        jPanel4.add(jtPes_Agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        jtPes_Solid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPes_SolidActionPerformed(evt);
            }
        });
        jtPes_Solid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPes_SolidKeyReleased(evt);
            }
        });
        jPanel4.add(jtPes_Solid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        jtPes_Aire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPes_AireActionPerformed(evt);
            }
        });
        jtPes_Aire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPes_AireKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPes_AireKeyTyped(evt);
            }
        });
        jPanel4.add(jtPes_Aire, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 70, -1));

        jCB_PesoAire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_PesoAireActionPerformed(evt);
            }
        });
        jPanel4.add(jCB_PesoAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));
        jPanel4.add(CB_PesoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 240, 200));

        jPanelDatos.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 560, 250));

        panelQCalc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Que desea calcular?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelQCalc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRelacionesVolumetricas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relaciones Volumétricas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanelRelacionesVolumetricas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBRelacionVacio.setText("Relación de vacíos (e)");
        jCBRelacionVacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRelacionVacioActionPerformed(evt);
            }
        });
        jPanelRelacionesVolumetricas.add(jCBRelacionVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCBPorosidad.setText("Porosidad (n)");
        jCBPorosidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPorosidadActionPerformed(evt);
            }
        });
        jPanelRelacionesVolumetricas.add(jCBPorosidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jCBGradoSaturacion.setText("Grado de Saturación (S)");
        jCBGradoSaturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGradoSaturacionActionPerformed(evt);
            }
        });
        jPanelRelacionesVolumetricas.add(jCBGradoSaturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        panelQCalc.add(jPanelRelacionesVolumetricas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 100));

        jPanelRelacionesGravimetricas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relaciones Gravimétricas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanelRelacionesGravimetricas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBContenidoHumedad.setText("Contenido de humedad (w)");
        jCBContenidoHumedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBContenidoHumedadActionPerformed(evt);
            }
        });
        jPanelRelacionesGravimetricas.add(jCBContenidoHumedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCBPesoEspecifico.setText("Peso específico (Y)");
        jCBPesoEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPesoEspecificoActionPerformed(evt);
            }
        });
        jPanelRelacionesGravimetricas.add(jCBPesoEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jCBPesoEspecificoSeco.setText("Peso específico seco (Yd)");
        jCBPesoEspecificoSeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPesoEspecificoSecoActionPerformed(evt);
            }
        });
        jPanelRelacionesGravimetricas.add(jCBPesoEspecificoSeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jCBGravedadEspecifica.setText("Gravedad especifica (Gs)");
        jCBGravedadEspecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGravedadEspecificaActionPerformed(evt);
            }
        });
        jPanelRelacionesGravimetricas.add(jCBGravedadEspecifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        panelQCalc.add(jPanelRelacionesGravimetricas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 370, 100));

        jPanelDatos.add(panelQCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 720, 150));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Muestra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNormal.setText("Normal");
        jButtonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNormalActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        jButtonSaturado.setText("Saturado");
        jButtonSaturado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaturadoActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSaturado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, -1));

        jPanelDatos.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 250, 80));

        getContentPane().add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1320, 290));

        jPanelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanelResultados.setToolTipText("Datos");
        jPanelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtArea_Resultado.setColumns(20);
        TxtArea_Resultado.setRows(5);
        jScrollPane1.setViewportView(TxtArea_Resultado);

        jScrollPane3.setViewportView(jScrollPane1);

        jPanelResultados.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, 300));

        getContentPane().add(jPanelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 490, 340));

        B_Calcular.setText("Calcular");
        B_Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CalcularMouseClicked(evt);
            }
        });
        B_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(B_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 80, 50));

        B_Procedimiento.setText("Mostrar Procedimiento");
        getContentPane().add(B_Procedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 640, -1, 40));

        B_Formulas.setText("Fórmulas");
        getContentPane().add(B_Formulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 580, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtVol_AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtVol_AguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtVol_AguaActionPerformed

    private void jtPes_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPes_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPes_TotalActionPerformed

    private void jtVol_solidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtVol_solidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtVol_solidosActionPerformed

    private void jtVol_AireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtVol_AireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtVol_AireActionPerformed

    private void jtVol_VacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtVol_VacioActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jtVol_VacioActionPerformed

    private void jtPes_AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPes_AguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPes_AguaActionPerformed

    private void jtPes_SolidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPes_SolidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPes_SolidActionPerformed

    private void jtPes_AireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPes_AireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPes_AireActionPerformed

    private void B_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CalcularActionPerformed
        // TODO add your handling code here:
        //evento cantidad boton
        count++;
        if (count > 1) {
            TxtArea_Resultado.setText("");
        }
        //
        if (jCBRelacionVacio.isSelected() == true || jCBGradoSaturacion.isSelected() == true || jCBPorosidad.isSelected() == true) {
            TxtArea_Resultado.append("                                   Relaciones Volumétricas     " + "\n" + "\n");
        }
        //Relacion de Vacios
        if (jCBRelacionVacio.isSelected() == true) {
            Rel_V_P.setRelacion_vacios(volumen.getVol_Vacios(), volumen.getVol_Solidos());
            TxtArea_Resultado.append("Relación de Vacios: " + Double.toString(Rel_V_P.getRelacion_vacios()) + "\n");
        }
        //Porosidad
        if (jCBPorosidad.isSelected() == true) {
            Rel_V_P.setPorosidad(volumen.getVol_Vacios(), volumen.getVol_Total());
            TxtArea_Resultado.append("Porosidad: " + Rel_V_P.getPorosidad() + "%" + "\n");
        }
        //Grado de Saturación
        if (jCBGradoSaturacion.isSelected() == true) {
            Rel_V_P.setGrado_Saturacion(volumen.getVol_Agua(), volumen.getVol_Vacios());
            TxtArea_Resultado.append("Grado de Saturación: " + Double.toString(Rel_V_P.getGrado_Saturacion()) + "%" + "\n");
        }
        if (jCBContenidoHumedad.isSelected() == true || jCBPesoEspecifico.isSelected() == true || jCBPesoEspecificoSeco.isSelected() == true || jCBGravedadEspecifica.isSelected() == true) {
            TxtArea_Resultado.append("                                   Relaciones Gravimétricas    " + "\n" + "\n");
        }
        //Contenido de Humedad
        if (jCBContenidoHumedad.isSelected() == true) {
            Rel_V_P.setHumedad(peso.getPes_Agua(), peso.getPes_Solidos());
            TxtArea_Resultado.append("Humedad: " + Double.toString(Rel_V_P.getHumedad()) + "%" + "\n");
        }
        //Peso Especifico
        if (jCBPesoEspecifico.isSelected() == true) {
            Rel_V_P.setPeso_Espec(peso.getPes_Total(), volumen.getVol_Total());
            TxtArea_Resultado.append("Peso Específico: " + Double.toString(Rel_V_P.getPeso_Espec()) + "g/cm3" + "\n");
        }
        //Peso Especifico Seco
        if (jCBPesoEspecificoSeco.isSelected() == true) {
            Rel_V_P.setPeso_Espec_Seco(peso.getPes_Solidos(), volumen.getVol_Total());
            TxtArea_Resultado.append("Peso Específico Seco: " + Double.toString(Rel_V_P.getPeso_Espec_Seco()) + "g/cm3" + "\n");
        }
        //Gravedad Especifica de Solidos
        if (jCBGravedadEspecifica.isSelected() == true) {
            Rel_V_P.setGrav_Espec_sol(peso.getPes_Solidos(), volumen.getVol_Solidos());
            TxtArea_Resultado.append("Gravedad Específica: " + Double.toString(Rel_V_P.getGrav_Espec_sol()) + "g/cm3" + "\n");
        }
    }//GEN-LAST:event_B_CalcularActionPerformed

    private void B_CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CalcularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_B_CalcularMouseClicked

    private void jtVol_VacioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVol_VacioKeyReleased
        // TODO add your handling code here:

        String Vv = jtVol_Vacio.getText();
        if ((Vv.equals("") == false && Vv.matches("[a-z].*") == false) || Vv.contains(".")) {
            graf_Vv.setText(Vv);
            volumen.setVol_Vacios(Double.parseDouble(Vv));
        } else {
            graf_Vv.setText("");
        }

    }//GEN-LAST:event_jtVol_VacioKeyReleased

    private void jtVol_AguaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVol_AguaKeyReleased
        // TODO add your handling code here:

        String Vw = jtVol_Agua.getText();
        if ((Vw.equals("") == false && Vw.matches("[a-z].*") == false) || Vw.contains(".")) {
            graf_Vw.setText(Vw);
            volumen.setVol_Agua(Double.parseDouble(Vw));
        } else {
            graf_Vw.setText("");
        }
    }//GEN-LAST:event_jtVol_AguaKeyReleased

    private void jtVol_solidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVol_solidosKeyReleased
        // TODO add your handling code here:

        String Vs = jtVol_solidos.getText();
        if ((Vs.equals("") == false && Vs.matches("[a-z].*") == false) || Vs.contains(".")) {
            graf_Vs.setText(Vs);
            volumen.setVol_Solidos(Double.parseDouble(Vs));
        } else {
            graf_Vs.setText("");
        }

    }//GEN-LAST:event_jtVol_solidosKeyReleased

    private void jtVol_AireKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVol_AireKeyReleased
        // TODO add your handling code here:
        String Va = jtVol_Aire.getText();
        if ((Va.equals("") == false && Va.matches("[a-z].*") == false) || Va.contains(".")) {
            graf_Va.setText(Va);
            volumen.setVol_Aire(Double.parseDouble(Va));
        } else {
            graf_Va.setText("");
        }

    }//GEN-LAST:event_jtVol_AireKeyReleased

    private void jtPes_AguaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPes_AguaKeyReleased
        // TODO add your handling code here:
        String Ww = jtPes_Agua.getText();
        if (Ww.equals("") == false && Ww.matches("[0-9]*")) {
            graf_Ww.setText(Ww);
        } else {
            graf_Ww.setText("");
        }
    }//GEN-LAST:event_jtPes_AguaKeyReleased

    private void jtPes_SolidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPes_SolidKeyReleased
        // TODO add your handling code here:
        String Ws = jtPes_Solid.getText();
        if (Ws.equals("") == false && Ws.matches("[0-9]*")) {
            graf_Ws.setText(Ws);
        } else {
            graf_Ws.setText("");
        }
    }//GEN-LAST:event_jtPes_SolidKeyReleased

    private void jtPes_AireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPes_AireKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jtPes_AireKeyTyped

    private void jtPes_TotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPes_TotalKeyReleased
        // TODO add your handling code here:
        /*String Wt = jtPes_Total.getText();
        if (Wt.equals("") == false && Wt.matches("[0-9]*")) {
            graf_Wt.setText(Wt);
        } else {
            graf_Wt.setText("");
        }*/
    }//GEN-LAST:event_jtPes_TotalKeyReleased

    private void jtPes_AireKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPes_AireKeyReleased
        // TODO add your handling code here:
        String Wa = jtPes_Aire.getText();
        if (Wa.equals("") == false && Wa.matches("[0-9]*")) {
            graf_Wa.setText(Wa);
        } else {
            graf_Wa.setText("");
        }
    }//GEN-LAST:event_jtPes_AireKeyReleased

    private void jCBRelacionVacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRelacionVacioActionPerformed
        // TODO add your handling code here:
        if (jCBRelacionVacio.isSelected() == true) {
            if (jtVol_Vacio.isEnabled() == false) {
                jtVol_Vacio.setEnabled(true);
            }
            if (jtVol_solidos.isEnabled() == false) {
                jtVol_solidos.setEnabled(true);
            }
        } else {
            if (jCBPorosidad.isSelected() == true || jCBGradoSaturacion.isSelected() == true) {
                jtVol_Vacio.setEnabled(true);
            } else {
                jtVol_Vacio.setEnabled(false);
                jtVol_Vacio.setText("");
            }
            if (jCBGravedadEspecifica.isSelected() == true) {
                jtVol_solidos.setEnabled(true);
            } else {
                jtVol_solidos.setEnabled(false);
                jtVol_solidos.setText("");
            }
        }
    }//GEN-LAST:event_jCBRelacionVacioActionPerformed

    private void jCBPorosidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPorosidadActionPerformed
        // TODO add your handling code here:
        if (jCBPorosidad.isSelected() == true) {
            if (jtVol_Vacio.isEnabled() == false) {
                jtVol_Vacio.setEnabled(true);
            }
            if (jtVol_Total.isEnabled() == false) {
                jtVol_Total.setEnabled(true);
            }
        } else {
            if (jCBRelacionVacio.isSelected() == true || jCBPorosidad.isSelected() == true) {
                jtVol_Vacio.setEnabled(true);
            } else {
                jtVol_Vacio.setEnabled(false);
            }
            if (jCBPesoEspecifico.isSelected() == true || jCBPesoEspecificoSeco.isSelected() == true) {
                jtVol_Total.setEnabled(true);
            } else {
                jtVol_Total.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jCBPorosidadActionPerformed

    private void jCBGradoSaturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGradoSaturacionActionPerformed
        // TODO add your handling code here:
        if (jCBGradoSaturacion.isSelected() == true) {
            if (jtVol_Vacio.isEnabled() == false) {
                jtVol_Vacio.setEnabled(true);
            }
            if (jtVol_Agua.isEnabled() == false) {
                jtVol_Agua.setEnabled(true);
            }
        } else {
            if (jCBRelacionVacio.isSelected() == true || jCBPorosidad.isSelected() == true) {
                jtVol_Vacio.setEnabled(true);
            } else {
                jtVol_Vacio.setEnabled(false);
            }
            jtVol_Agua.setEnabled(false);
        }
    }//GEN-LAST:event_jCBGradoSaturacionActionPerformed

    private void jCBContenidoHumedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBContenidoHumedadActionPerformed
        // TODO add your handling code here:
        if (jCBContenidoHumedad.isSelected() == true) {
            if (jtPes_Agua.isEnabled() == false) {
                jtPes_Agua.setEnabled(true);
            }
            if (jtPes_Solid.isEnabled() == false) {
                jtPes_Solid.setEnabled(true);
            }
        } else {
            if (jCBPesoEspecifico.isSelected() == true || jCBGravedadEspecifica.isSelected() == true) {
                jtPes_Solid.setEnabled(true);
            } else {
                jtPes_Solid.setEnabled(false);
            }
            jtPes_Agua.setEnabled(false);
        }
    }//GEN-LAST:event_jCBContenidoHumedadActionPerformed

    private void jCBPesoEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPesoEspecificoActionPerformed
        // TODO add your handling code here:
        if (jCBPesoEspecifico.isSelected() == true) {
            if (jtVol_Total.isEnabled() == false) {
                jtVol_Total.setEnabled(true);
            }
            if (jtPes_Total.isEnabled() == false) {
                jtPes_Total.setEnabled(true);
            }
        } else {
            if (jCBPesoEspecificoSeco.isSelected() == true || jCBPorosidad.isSelected() == true) {
                jtVol_Total.setEnabled(true);
            } else {
                jtVol_Total.setEnabled(false);
            }
            jtPes_Total.setEnabled(false);
        }
    }//GEN-LAST:event_jCBPesoEspecificoActionPerformed

    private void jCBPesoEspecificoSecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPesoEspecificoSecoActionPerformed
        // TODO add your handling code here:
        if (jCBPesoEspecificoSeco.isSelected() == true) {
            if (jtPes_Solid.isEnabled() == false) {
                jtPes_Solid.setEnabled(true);
            }
            if (jtPes_Total.isEnabled() == false) {
                jtPes_Total.setEnabled(true);
            }
        } else {
            if (jCBGravedadEspecifica.isSelected() == true || jCBContenidoHumedad.isSelected() == true) {
                jtPes_Solid.setEnabled(true);
            } else {
                jtPes_Solid.setEnabled(false);
            }
            if (jCBPesoEspecifico.isSelected() == true || jCBContenidoHumedad.isSelected() == true) {
                jtVol_Total.setEnabled(true);
            } else {
                jtPes_Total.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jCBPesoEspecificoSecoActionPerformed

    private void jCBGravedadEspecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGravedadEspecificaActionPerformed
        // TODO add your handling code here:
        if (jCBGravedadEspecifica.isSelected() == true) {
            if (jtVol_solidos.isEnabled() == false) {
                jtVol_solidos.setEnabled(true);
            }
            if (jtPes_Solid.isEnabled() == false) {
                jtPes_Solid.setEnabled(true);
            }
        } else {
            if (jCBPesoEspecificoSeco.isSelected() == true || jCBContenidoHumedad.isSelected() == true) {
                jtPes_Solid.setEnabled(true);
            } else {
                jtPes_Solid.setEnabled(false);
            }
            if (jCBRelacionVacio.isSelected() == true) {
                jtVol_solidos.setEnabled(true);
            } else {
                jtVol_solidos.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jCBGravedadEspecificaActionPerformed

    private void jButtonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNormalActionPerformed
        // TODO add your handling code here:
        panelGaseoso.setVisible(true);
        flech1.setVisible(true);
        flech2.setVisible(true);
        flech3.setVisible(false);
        textaire.setVisible(true);
        textaire2.setVisible(true);
        jtVol_Aire.setVisible(true);
        jtPes_Aire.setVisible(true);
        texttitmuestra2.setVisible(false);
        texttitmuestra1.setVisible(true);
        jCB_VolAire.setVisible(true);
        jCB_PesoAire.setVisible(true);
    }//GEN-LAST:event_jButtonNormalActionPerformed

    private void jButtonSaturadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaturadoActionPerformed
        // TODO add your handling code here:
        panelGaseoso.setVisible(false);
        texttitmuestra1.setVisible(false);
        texttitmuestra2.setVisible(true);
        flech1.setVisible(false);
        flech2.setVisible(false);
        flech3.setVisible(true);
        textaire.setVisible(false);
        textaire2.setVisible(false);
        jtVol_Aire.setVisible(false);
        jtPes_Aire.setVisible(false);
        jCB_VolAire.setVisible(false);
        jCB_PesoAire.setVisible(false);

    }//GEN-LAST:event_jButtonSaturadoActionPerformed

    private void jCB_PesoAireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_PesoAireActionPerformed
        // TODO add your handling code here:
        if (jCB_PesoAire.isSelected() == true) {
            jtPes_Aire.setEnabled(true);
        } else {
            jtPes_Aire.setEnabled(false);
        }
    }//GEN-LAST:event_jCB_PesoAireActionPerformed

    private void jCB_VolAireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_VolAireActionPerformed
        // TODO add your handling code here:
        if (jCB_VolAire.isSelected() == true) {
            jtVol_Aire.setEnabled(true);
        } else {
            jtVol_Aire.setEnabled(false);
        }
    }//GEN-LAST:event_jCB_VolAireActionPerformed

    private void CB_VolTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_VolTotalActionPerformed
        // TODO add your handling code here:
        String V1 = jtVol_Vacio.getText();
        String V2 = jtVol_Agua.getText();
        String V3 = jtVol_Aire.getText();
        String V4 = jtVol_solidos.getText();
        String V5 = jtVol_Total.getText();

        
            volumen.setVol_Agua(Double.parseDouble(V2));
            volumen.setVol_Aire(Double.parseDouble(V3));
            volumen.setVol_Vacios(Double.parseDouble(V1));
            volumen.setVol_Solidos(Double.parseDouble(V4));
            volumen.setVol_Total(Double.parseDouble(V5));

        if (CB_VolTotal.isSelected() == true) {
            jtVol_Total.setEnabled(true);
            jtVol_Total.setText(Double.toString(volumen.getVol_Total()));
            graf_Vt.setText(Double.toString(volumen.getVol_Total()));
        } else {
            jtVol_Total.setEnabled(false);
        }

    }//GEN-LAST:event_CB_VolTotalActionPerformed

    private void jtVol_TotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVol_TotalKeyReleased
        // TODO add your handling code here:
        String Vt = jtVol_Total.getText();
        if ((Vt.equals("") == false && Vt.matches("[a-z].*") == false) || Vt.contains(".")) {
            graf_Vt.setText(Vt);
            volumen.setVol_Total(Double.parseDouble(Vt));
            jtVol_Vacio.setText("0");
            jtVol_Aire.setText("0");
            jtVol_solidos.setText("0");
            jtVol_Agua.setText("0");

        } else {
            graf_Vt.setText("");

        }
    }//GEN-LAST:event_jtVol_TotalKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Calcular;
    private javax.swing.JButton B_Formulas;
    private javax.swing.JButton B_Procedimiento;
    private javax.swing.JCheckBox CB_PesoTotal;
    private javax.swing.JCheckBox CB_VolTotal;
    private javax.swing.JTextArea TxtArea_Resultado;
    private javax.swing.JPanel flech1;
    private javax.swing.JPanel flech2;
    private javax.swing.JPanel flech3;
    private javax.swing.JTextField graf_Va;
    private javax.swing.JTextField graf_Vs;
    private javax.swing.JTextField graf_Vt;
    private javax.swing.JTextField graf_Vv;
    private javax.swing.JTextField graf_Vw;
    private javax.swing.JTextField graf_Wa;
    private javax.swing.JTextField graf_Ws;
    private javax.swing.JTextField graf_Wt;
    private javax.swing.JTextField graf_Ww;
    private javax.swing.JButton jButtonNormal;
    private javax.swing.JButton jButtonSaturado;
    private javax.swing.JCheckBox jCBContenidoHumedad;
    private javax.swing.JCheckBox jCBGradoSaturacion;
    private javax.swing.JCheckBox jCBGravedadEspecifica;
    private javax.swing.JCheckBox jCBPesoEspecifico;
    private javax.swing.JCheckBox jCBPesoEspecificoSeco;
    private javax.swing.JCheckBox jCBPorosidad;
    private javax.swing.JCheckBox jCBRelacionVacio;
    private javax.swing.JCheckBox jCB_PesoAire;
    private javax.swing.JCheckBox jCB_VolAire;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFASELIQUIDA;
    private javax.swing.JLabel jLabelFASESOLIDA;
    private javax.swing.JLabel jLabelPESO;
    private javax.swing.JLabel jLabelTitulodelAplicativo;
    private javax.swing.JLabel jLabelVOLUMEN;
    private javax.swing.JLabel jLabelVs;
    private javax.swing.JLabel jLabelVt;
    private javax.swing.JLabel jLabelVw;
    private javax.swing.JLabel jLabelWs;
    private javax.swing.JLabel jLabelWt;
    private javax.swing.JLabel jLabelWw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelGraficaMuestra;
    private javax.swing.JPanel jPanelRelacionesGravimetricas;
    private javax.swing.JPanel jPanelRelacionesVolumetricas;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtPes_Agua;
    private javax.swing.JTextField jtPes_Aire;
    private javax.swing.JTextField jtPes_Solid;
    private javax.swing.JTextField jtPes_Total;
    private javax.swing.JTextField jtVol_Agua;
    private javax.swing.JTextField jtVol_Aire;
    private javax.swing.JTextField jtVol_Total;
    private javax.swing.JTextField jtVol_Vacio;
    private javax.swing.JTextField jtVol_solidos;
    private javax.swing.JPanel panelGaseoso;
    private javax.swing.JPanel panelQCalc;
    private javax.swing.JLabel textaire;
    private javax.swing.JLabel textaire2;
    private javax.swing.JLabel texttitmuestra1;
    private javax.swing.JLabel texttitmuestra2;
    // End of variables declaration//GEN-END:variables
}
